name: release_cocoapod

on:
  push:
    tags:
      - '*'
      
  workflow_dispatch:
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: true 
          fetch-depth: 0 
        
      - name: Clone the sdk repo
        run: |
          git clone https://${{ secrets.GH_USERNAME }}:${{ secrets.GH_TOKEN }}@github.com/amityadav85/aydice-lib.git libclone

      - name: Run build Script
        working-directory: ./libclone
        run: |
           chmod +x xcode_build.sh
           sh xcode_build.sh
        shell: bash
        
      - name: Update framework file to repo
        working-directory: ./
        run: |
          rm -rf ./AYDice.xcframework
          mv ./libclone/AYDice.xcframework ./AYDice.xcframework
          git config --global user.email "amit15885@gmail.com"
          git config --global user.name "${{ secrets.GH_USERNAME }}"

          git add AYDice.xcframework
          git commit -m "Updating framework file to latest"
          git tag $(git describe --tags `git rev-list --tags --max-count=1`) -f
          git push "https://${{ secrets.GH_USERNAME }}: ${{ secrets.GH_TOKEN }}@github.com/amityadav85/aydice-lib.git" --tags -f
        shell: bash
