name: release_cocoapod

on:
  push:
    tags:
      - 'v*.*.*'
      
  workflow_dispatch:
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false 
          fetch-depth: 0 
      
      - name: Clone the sdk repo
        run: |
          git clone https://${{ secrets.GH_USERNAME }}:${{ secrets.GH_TOKEN }}@github.com/amityadav85/aydice-lib.git libclone
        shell: bash
        
      - name: Run build Script
        working-directory: ./libclone
        run: |
           chmod +x xcode_build.sh
           sh xcode_build.sh
        shell: bash
        
      - name: Update framework file to repo
        run: |
          rm -rf ./AYDice.xcframework
          mv ./libclone/AYDice.xcframework ./AYDice.xcframework
          git config --global user.email "amit15885@gmail.com"
          git config --global user.name "${{ secrets.GH_USERNAME }}"
          git remote set-url --push origin https://${{ secrets.GH_USERNAME }}:${{ secrets.GH_TOKEN }}@github.com/amityadav85/aypod.git
          VER=${GITHUB_REF#refs/*/}
          SVER="${VER//v}"
          git push --delete origin ${VER}
          git add AYDice.xcframework
          git commit -m "Updating framework file to latest"
          git tag ${SVER}
          git push origin ${SVER}
          git push origin HEAD:main
        shell: bash
      
      # Install Cocoapods on the machine
      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Deploy to Cocoapods
        run: |
          set -eo pipefail
          export POD_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
          pod lib lint --allow-warnings
          pod trunk push --allow-warnings
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
