name: release_cocoapod

on:
  push:
    tags:
      - '*'
      
  workflow_dispatch:
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: true 
          fetch-depth: 0 
        
      - name: Clone the sdk repo
        run: |
          git clone https://github.com/amityadav85/aydice-lib.git libclone

      - name: Run build Script
        working-directory: ./libclone
        run: |
           chmod +x xcode_build.sh
           sh xcode_build.sh
        shell: bash
        
      - name: Update framework file to repo
        working-directory: ./
        run: |
          rm -rf ./AYDice.xcframework
          mv ./libclone/AYDice.xcframework ./AYDice.xcframework
          git config --global user.email "amit15885@gmail.com"
          git config --global user.name "${{ secrets.GH_USERNAME }}"

          git add AYDice.xcframework
          git commit -m "Updating framework file to latest"
          git tag -a "$(git describe --tags `git rev-list --tags --max-count=1`)" -m "moved tag to latest"
          git push origin "$(git describe --tags `git rev-list --tags --max-count=1`)"
          git push origin
        shell: bash
      
      # Install Cocoapods on the machine
      - name: Install Cocoapods
        run: gem install cocoapods
        
      - name: Deploy to Cocoapods
        run: |
          set -eo pipefail
          export POD_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
          pod lib lint --allow-warnings
          pod trunk push --allow-warnings
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
