name: release_cocoapod

on:
  push:
    tags:
      - '*'
      
  workflow_dispatch:
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Clone the sdk repo
        run: |
          git clone https://amityadav85:${{ secrets.GH_TOKEN }}@github.com/amityadav85/aydice-lib.git libclone

      - name: Run build Script
        working-directory: ./libclone
        run: |
           chmod +x xcode_build.sh
           sh xcode_build.sh
        shell: bash
      - name: list files
        uses: enricomarino/actions@v2
        with:
          source: ./libclone
