# This is a basic workflow to help you get started with Actions

name: release_cocoapod

# Controls when the workflow will run
on:
  push:
    tags:
      - '*'
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Install Cocoapods on the machine
      - name: Install Cocoapods
        run: gem install cocoapods
  
      - name: Clone the sdk repo
        run: |
          git clone https://amityadav85:${{ secrets.GH_TOKEN }}@github.com/amityadav85/aydice-lib.git libclone
          
      - name: Run build Script
        working-directory: ./libclone
        run: |
           chmod +x ./xcode_build.sh
           xcode_build.sh
        shell: bash
